[package]
name = "v1per-servicing"
version = "1.0.0"
description = "Android servicing toolkit"
authors = ["coolishsec0175"]
edition = "2021"

[lib]
name = "v1per_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
zip = { version = "2", default-features = false, features = ["deflate"] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
penumbra-mtk = { path = "crates/penumbra-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
dirs = "5"
open = "5"
rfd = "0.15"
reqwest = { version = "0.12", features = ["blocking", "json"] }
zip = { version = "2", default-features = false, features = ["deflate"] }
sha2 = "0.10"
serialport = "4"
flate2 = "1"
lzma-rs = "0.3"
bzip2-rs = "0.1"

[target.'cfg(windows)'.dependencies]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
overflow-checks = false
debug = false

[profile.release.package."*"]
opt-level = "s"
strip = true
debug = false

[profile.release.package.lzma-rs]
opt-level = 3

