export const WIN_MAIN_RENDERER_EVENT_NAME = {
  get_env_params: 'get_env_params',
  system_theme_change: 'system_theme_change',
  theme_change: 'theme_change',
  get_system_fonts: 'get_system_fonts',
  get_app_setting: 'get_app_setting',
  set_app_setting: 'set_app_setting',
  focus: 'focus',
  close: 'close',
  min: 'min',
  max: 'max',
  fullscreen: 'fullscreen',
  set_app_name: 'set_app_name',
  clear_cache: 'clear_cache',
  get_cache_size: 'get_cache_size',
  inited: 'inited',
  show_save_dialog: 'show_save_dialog',
  show_select_dialog: 'show_select_dialog',
  show_dialog: 'show_dialog',
  open_dir_in_explorer: 'open_dir_in_explorer',
  open_dev_tools: 'open_dev_tools',
  set_power_save_blocker: 'set_power_save_blocker',
  change_tray: 'change_tray',
  quit_update: 'quit_update',
  update_check: 'update_check',
  update_download_update: 'update_download_update',
  update_available: 'update_available',
  update_error: 'update_error',
  update_progress: 'update_progress',
  update_downloaded: 'update_downloaded',
  update_not_available: 'update_not_available',
  set_ignore_mouse_events: 'set_ignore_mouse_events',
  set_window_size: 'set_window_size',
  restart_window: 'restart_window',
  quit: 'quit',
  min_toggle: 'min_toggle',
  hide_toggle: 'hide_toggle',
  tray_show: 'tray_show',
  tray_hide: 'tray_hide',
  hotKey_register: 'hotKey_register',
  hotKey_unregister: 'hotKey_unregister',
  hotKey_update_config: 'hotKey_update_config',
  get_hot_key: 'get_hot_key',
  key_down: 'key_down',
  set_hot_key_config: 'set_hot_key_config',
  on_config_change: 'on_config_change',
  get_themes: 'get_themes',
  save_theme: 'save_theme',
  remove_theme: 'remove_theme',
}

export const HOTKEY_RENDERER_EVENT_NAME = {
  get_hot_key: 'get_hot_key',
  key_down: 'key_down',
  set_hot_key_config: 'set_hot_key_config',
  set_config: 'set_config',
  status: 'status',
  enable: 'enable',
}

export const CMMON_EVENT_NAME = {
  ...WIN_MAIN_RENDERER_EVENT_NAME,
  ...HOTKEY_RENDERER_EVENT_NAME,
}

export const WIN_MAIN_RENDERER_CHANNEL_NAME = WIN_MAIN_RENDERER_EVENT_NAME
export const WIN_MAIN_IPC_NAME = WIN_MAIN_RENDERER_EVENT_NAME
