const modules = {
  common: {
    get_env_params: 'get_env_params',
    deeplink: 'deeplink',
    clear_env_params_deeplink: 'clear_env_params_deeplink',
    system_theme_change: 'system_theme_change',
    theme_change: 'theme_change',
    get_system_fonts: 'get_system_fonts',
    get_app_setting: 'get_app_setting',
    set_app_setting: 'set_app_setting',
  },
  winMain: {
    focus: 'focus',
    close: 'close',
    min: 'min',
    max: 'max',
    fullscreen: 'fullscreen',
    set_app_name: 'set_app_name',
    clear_cache: 'clear_cache',
    get_cache_size: 'get_cache_size',
    inited: 'inited',
    show_save_dialog: 'show_save_dialog',
    show_select_dialog: 'show_select_dialog',
    show_dialog: 'show_dialog',
    open_dir_in_explorer: 'open_dir_in_explorer',
    open_dev_tools: 'open_dev_tools',
    set_power_save_blocker: 'set_power_save_blocker',
    change_tray: 'change_tray',
    quit_update: 'quit_update',
    update_check: 'update_check',
    update_download_update: 'update_download_update',
    update_available: 'update_available',
    update_error: 'update_error',
    update_progress: 'update_progress',
    update_downloaded: 'update_downloaded',
    update_not_available: 'update_not_available',
    set_ignore_mouse_events: 'set_ignore_mouse_events',
    set_window_size: 'set_window_size',
    restart_window: 'restart_window',
  },
  tray: {
    show: 'show',
    hide: 'hide',
  },
  hotKey: {
    register: 'register',
    unregister: 'unregister',
    update_config: 'update_config',
  },
  sync: {
    action: 'sync_action',
    get_server_devices: 'sync_get_server_devices',
    remove_server_device: 'sync_remove_server_device',
  },
  userApi: {
    import_user_api: 'import_user_api',
    remove_user_api: 'remove_user_api',
    set_user_api: 'set_user_api',
    get_user_api_list: 'get_user_api_list',
    get_user_api_status: 'get_user_api_status',
    user_api_set_allow_update_alert: 'user_api_set_allow_update_alert',
    request_user_api: 'request_user_api',
    request_user_api_cancel: 'request_user_api_cancel',
  },
  openApi: {
    open_api_action: 'open_api_action',
  },
}

export const WIN_MAIN_RENDERER_EVENT_NAME = modules
export const WIN_MAIN_RENDERER_CHANNEL_NAME = {
  ...modules.common,
  ...modules.winMain,
  ...modules.tray,
  ...modules.hotKey,
  ...modules.sync,
  ...modules.userApi,
  ...modules.openApi,
}
export const WIN_MAIN_IPC_NAME = {
  ...modules.common,
  ...modules.winMain,
  ...modules.tray,
  ...modules.hotKey,
}
